package polymarket

import "time"

type Event struct {
	ID                string    `json:"id"`
	Ticker            string    `json:"ticker"`
	Slug              string    `json:"slug"`
	Title             string    `json:"title"`
	Subtitle          string    `json:"subtitle"`
	Description       string    `json:"description"`
	ResolutionSource  string    `json:"resolutionSource"`
	StartDate         time.Time `json:"startDate"`
	CreationDate      time.Time `json:"creationDate"`
	EndDate           time.Time `json:"endDate"`
	Image             string    `json:"image"`
	Icon              string    `json:"icon"`
	Active            bool      `json:"active"`
	Closed            bool      `json:"closed"`
	Archived          bool      `json:"archived"`
	New               bool      `json:"new"`
	Featured          bool      `json:"featured"`
	Restricted        bool      `json:"restricted"`
	Liquidity         int       `json:"liquidity"`
	Volume            int       `json:"volume"`
	OpenInterest      int       `json:"openInterest"`
	SortBy            string    `json:"sortBy"`
	Category          string    `json:"category"`
	Subcategory       string    `json:"subcategory"`
	IsTemplate        bool      `json:"isTemplate"`
	TemplateVariables string    `json:"templateVariables"`
	PublishedAt       string    `json:"published_at"`
	CreatedBy         string    `json:"createdBy"`
	UpdatedBy         string    `json:"updatedBy"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
	CommentsEnabled   bool      `json:"commentsEnabled"`
	Competitive       int       `json:"competitive"`
	Volume24Hr        int       `json:"volume24hr"`
	Volume1Wk         int       `json:"volume1wk"`
	Volume1Mo         int       `json:"volume1mo"`
	Volume1Yr         int       `json:"volume1yr"`
	FeaturedImage     string    `json:"featuredImage"`
	DisqusThread      string    `json:"disqusThread"`
	ParentEvent       string    `json:"parentEvent"`
	EnableOrderBook   bool      `json:"enableOrderBook"`
	LiquidityAmm      int       `json:"liquidityAmm"`
	LiquidityClob     int       `json:"liquidityClob"`
	NegRisk           bool      `json:"negRisk"`
	NegRiskMarketID   string    `json:"negRiskMarketID"`
	NegRiskFeeBips    int       `json:"negRiskFeeBips"`
	CommentCount      int       `json:"commentCount"`
	ImageOptimized    struct {
		ID                        string `json:"id"`
		ImageURLSource            string `json:"imageUrlSource"`
		ImageURLOptimized         string `json:"imageUrlOptimized"`
		ImageSizeKbSource         int    `json:"imageSizeKbSource"`
		ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
		ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
		ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
		RelID                     int    `json:"relID"`
		Field                     string `json:"field"`
		Relname                   string `json:"relname"`
	} `json:"imageOptimized"`
	IconOptimized struct {
		ID                        string `json:"id"`
		ImageURLSource            string `json:"imageUrlSource"`
		ImageURLOptimized         string `json:"imageUrlOptimized"`
		ImageSizeKbSource         int    `json:"imageSizeKbSource"`
		ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
		ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
		ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
		RelID                     int    `json:"relID"`
		Field                     string `json:"field"`
		Relname                   string `json:"relname"`
	} `json:"iconOptimized"`
	FeaturedImageOptimized struct {
		ID                        string `json:"id"`
		ImageURLSource            string `json:"imageUrlSource"`
		ImageURLOptimized         string `json:"imageUrlOptimized"`
		ImageSizeKbSource         int    `json:"imageSizeKbSource"`
		ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
		ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
		ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
		RelID                     int    `json:"relID"`
		Field                     string `json:"field"`
		Relname                   string `json:"relname"`
	} `json:"featuredImageOptimized"`
	SubEvents []string `json:"subEvents"`
	Markets   []struct {
		ID                    string    `json:"id"`
		Question              string    `json:"question"`
		ConditionID           string    `json:"conditionId"`
		Slug                  string    `json:"slug"`
		TwitterCardImage      string    `json:"twitterCardImage"`
		ResolutionSource      string    `json:"resolutionSource"`
		EndDate               time.Time `json:"endDate"`
		Category              string    `json:"category"`
		AmmType               string    `json:"ammType"`
		Liquidity             string    `json:"liquidity"`
		SponsorName           string    `json:"sponsorName"`
		SponsorImage          string    `json:"sponsorImage"`
		StartDate             time.Time `json:"startDate"`
		XAxisValue            string    `json:"xAxisValue"`
		YAxisValue            string    `json:"yAxisValue"`
		DenominationToken     string    `json:"denominationToken"`
		Fee                   string    `json:"fee"`
		Image                 string    `json:"image"`
		Icon                  string    `json:"icon"`
		LowerBound            string    `json:"lowerBound"`
		UpperBound            string    `json:"upperBound"`
		Description           string    `json:"description"`
		Outcomes              string    `json:"outcomes"`
		OutcomePrices         string    `json:"outcomePrices"`
		Volume                string    `json:"volume"`
		Active                bool      `json:"active"`
		MarketType            string    `json:"marketType"`
		FormatType            string    `json:"formatType"`
		LowerBoundDate        string    `json:"lowerBoundDate"`
		UpperBoundDate        string    `json:"upperBoundDate"`
		Closed                bool      `json:"closed"`
		MarketMakerAddress    string    `json:"marketMakerAddress"`
		CreatedBy             int       `json:"createdBy"`
		UpdatedBy             int       `json:"updatedBy"`
		CreatedAt             time.Time `json:"createdAt"`
		UpdatedAt             time.Time `json:"updatedAt"`
		ClosedTime            string    `json:"closedTime"`
		WideFormat            bool      `json:"wideFormat"`
		New                   bool      `json:"new"`
		MailchimpTag          string    `json:"mailchimpTag"`
		Featured              bool      `json:"featured"`
		Archived              bool      `json:"archived"`
		ResolvedBy            string    `json:"resolvedBy"`
		Restricted            bool      `json:"restricted"`
		MarketGroup           int       `json:"marketGroup"`
		GroupItemTitle        string    `json:"groupItemTitle"`
		GroupItemThreshold    string    `json:"groupItemThreshold"`
		QuestionID            string    `json:"questionID"`
		UmaEndDate            string    `json:"umaEndDate"`
		EnableOrderBook       bool      `json:"enableOrderBook"`
		OrderPriceMinTickSize int       `json:"orderPriceMinTickSize"`
		OrderMinSize          int       `json:"orderMinSize"`
		UmaResolutionStatus   string    `json:"umaResolutionStatus"`
		CurationOrder         int       `json:"curationOrder"`
		VolumeNum             int       `json:"volumeNum"`
		LiquidityNum          int       `json:"liquidityNum"`
		EndDateIso            string    `json:"endDateIso"`
		StartDateIso          string    `json:"startDateIso"`
		UmaEndDateIso         string    `json:"umaEndDateIso"`
		HasReviewedDates      bool      `json:"hasReviewedDates"`
		ReadyForCron          bool      `json:"readyForCron"`
		CommentsEnabled       bool      `json:"commentsEnabled"`
		Volume24Hr            int       `json:"volume24hr"`
		Volume1Wk             int       `json:"volume1wk"`
		Volume1Mo             int       `json:"volume1mo"`
		Volume1Yr             int       `json:"volume1yr"`
		GameStartTime         string    `json:"gameStartTime"`
		SecondsDelay          int       `json:"secondsDelay"`
		ClobTokenIds          string    `json:"clobTokenIds"`
		DisqusThread          string    `json:"disqusThread"`
		ShortOutcomes         string    `json:"shortOutcomes"`
		TeamAID               string    `json:"teamAID"`
		TeamBID               string    `json:"teamBID"`
		UmaBond               string    `json:"umaBond"`
		UmaReward             string    `json:"umaReward"`
		FpmmLive              bool      `json:"fpmmLive"`
		Volume24HrAmm         int       `json:"volume24hrAmm"`
		Volume1WkAmm          int       `json:"volume1wkAmm"`
		Volume1MoAmm          int       `json:"volume1moAmm"`
		Volume1YrAmm          int       `json:"volume1yrAmm"`
		Volume24HrClob        int       `json:"volume24hrClob"`
		Volume1WkClob         int       `json:"volume1wkClob"`
		Volume1MoClob         int       `json:"volume1moClob"`
		Volume1YrClob         int       `json:"volume1yrClob"`
		VolumeAmm             int       `json:"volumeAmm"`
		VolumeClob            int       `json:"volumeClob"`
		LiquidityAmm          int       `json:"liquidityAmm"`
		LiquidityClob         int       `json:"liquidityClob"`
		MakerBaseFee          int       `json:"makerBaseFee"`
		TakerBaseFee          int       `json:"takerBaseFee"`
		CustomLiveness        int       `json:"customLiveness"`
		AcceptingOrders       bool      `json:"acceptingOrders"`
		NotificationsEnabled  bool      `json:"notificationsEnabled"`
		Score                 int       `json:"score"`
		ImageOptimized        struct {
			ID                        string `json:"id"`
			ImageURLSource            string `json:"imageUrlSource"`
			ImageURLOptimized         string `json:"imageUrlOptimized"`
			ImageSizeKbSource         int    `json:"imageSizeKbSource"`
			ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
			ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
			ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
			RelID                     int    `json:"relID"`
			Field                     string `json:"field"`
			Relname                   string `json:"relname"`
		} `json:"imageOptimized"`
		IconOptimized struct {
			ID                        string `json:"id"`
			ImageURLSource            string `json:"imageUrlSource"`
			ImageURLOptimized         string `json:"imageUrlOptimized"`
			ImageSizeKbSource         int    `json:"imageSizeKbSource"`
			ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
			ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
			ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
			RelID                     int    `json:"relID"`
			Field                     string `json:"field"`
			Relname                   string `json:"relname"`
		} `json:"iconOptimized"`
		Events     string `json:"events"`
		Categories []struct {
			ID             string    `json:"id"`
			Label          string    `json:"label"`
			ParentCategory string    `json:"parentCategory"`
			Slug           string    `json:"slug"`
			PublishedAt    string    `json:"publishedAt"`
			CreatedBy      string    `json:"createdBy"`
			UpdatedBy      string    `json:"updatedBy"`
			CreatedAt      time.Time `json:"createdAt"`
			UpdatedAt      time.Time `json:"updatedAt"`
		} `json:"categories"`
		Tags []struct {
			ID          string    `json:"id"`
			Label       string    `json:"label"`
			Slug        string    `json:"slug"`
			ForceShow   bool      `json:"forceShow"`
			PublishedAt string    `json:"publishedAt"`
			CreatedBy   int       `json:"createdBy"`
			UpdatedBy   int       `json:"updatedBy"`
			CreatedAt   time.Time `json:"createdAt"`
			UpdatedAt   time.Time `json:"updatedAt"`
			ForceHide   bool      `json:"forceHide"`
			IsCarousel  bool      `json:"isCarousel"`
		} `json:"tags"`
		Creator                      string    `json:"creator"`
		Ready                        bool      `json:"ready"`
		Funded                       bool      `json:"funded"`
		PastSlugs                    string    `json:"pastSlugs"`
		ReadyTimestamp               time.Time `json:"readyTimestamp"`
		FundedTimestamp              time.Time `json:"fundedTimestamp"`
		AcceptingOrdersTimestamp     time.Time `json:"acceptingOrdersTimestamp"`
		Competitive                  int       `json:"competitive"`
		RewardsMinSize               int       `json:"rewardsMinSize"`
		RewardsMaxSpread             int       `json:"rewardsMaxSpread"`
		Spread                       int       `json:"spread"`
		AutomaticallyResolved        bool      `json:"automaticallyResolved"`
		OneDayPriceChange            int       `json:"oneDayPriceChange"`
		OneHourPriceChange           int       `json:"oneHourPriceChange"`
		OneWeekPriceChange           int       `json:"oneWeekPriceChange"`
		OneMonthPriceChange          int       `json:"oneMonthPriceChange"`
		OneYearPriceChange           int       `json:"oneYearPriceChange"`
		LastTradePrice               int       `json:"lastTradePrice"`
		BestBid                      int       `json:"bestBid"`
		BestAsk                      int       `json:"bestAsk"`
		AutomaticallyActive          bool      `json:"automaticallyActive"`
		ClearBookOnStart             bool      `json:"clearBookOnStart"`
		ChartColor                   string    `json:"chartColor"`
		SeriesColor                  string    `json:"seriesColor"`
		ShowGmpSeries                bool      `json:"showGmpSeries"`
		ShowGmpOutcome               bool      `json:"showGmpOutcome"`
		ManualActivation             bool      `json:"manualActivation"`
		NegRiskOther                 bool      `json:"negRiskOther"`
		GameID                       string    `json:"gameId"`
		GroupItemRange               string    `json:"groupItemRange"`
		SportsMarketType             string    `json:"sportsMarketType"`
		Line                         int       `json:"line"`
		UmaResolutionStatuses        string    `json:"umaResolutionStatuses"`
		PendingDeployment            bool      `json:"pendingDeployment"`
		Deploying                    bool      `json:"deploying"`
		DeployingTimestamp           time.Time `json:"deployingTimestamp"`
		ScheduledDeploymentTimestamp time.Time `json:"scheduledDeploymentTimestamp"`
		RfqEnabled                   bool      `json:"rfqEnabled"`
		EventStartTime               time.Time `json:"eventStartTime"`
		FeesEnabled                  bool      `json:"feesEnabled"`
		FeeSchedule                  struct {
			Exponent   int  `json:"exponent"`
			Rate       int  `json:"rate"`
			TakerOnly  bool `json:"takerOnly"`
			RebateRate int  `json:"rebateRate"`
		} `json:"feeSchedule"`
	} `json:"markets"`
	Series []struct {
		ID                string    `json:"id"`
		Ticker            string    `json:"ticker"`
		Slug              string    `json:"slug"`
		Title             string    `json:"title"`
		Subtitle          string    `json:"subtitle"`
		SeriesType        string    `json:"seriesType"`
		Recurrence        string    `json:"recurrence"`
		Description       string    `json:"description"`
		Image             string    `json:"image"`
		Icon              string    `json:"icon"`
		Layout            string    `json:"layout"`
		Active            bool      `json:"active"`
		Closed            bool      `json:"closed"`
		Archived          bool      `json:"archived"`
		New               bool      `json:"new"`
		Featured          bool      `json:"featured"`
		Restricted        bool      `json:"restricted"`
		IsTemplate        bool      `json:"isTemplate"`
		TemplateVariables bool      `json:"templateVariables"`
		PublishedAt       string    `json:"publishedAt"`
		CreatedBy         string    `json:"createdBy"`
		UpdatedBy         string    `json:"updatedBy"`
		CreatedAt         time.Time `json:"createdAt"`
		UpdatedAt         time.Time `json:"updatedAt"`
		CommentsEnabled   bool      `json:"commentsEnabled"`
		Competitive       string    `json:"competitive"`
		Volume24Hr        int       `json:"volume24hr"`
		Volume            int       `json:"volume"`
		Liquidity         int       `json:"liquidity"`
		StartDate         time.Time `json:"startDate"`
		PythTokenID       string    `json:"pythTokenID"`
		CgAssetName       string    `json:"cgAssetName"`
		Score             int       `json:"score"`
		Events            string    `json:"events"`
		Collections       []struct {
			ID                string    `json:"id"`
			Ticker            string    `json:"ticker"`
			Slug              string    `json:"slug"`
			Title             string    `json:"title"`
			Subtitle          string    `json:"subtitle"`
			CollectionType    string    `json:"collectionType"`
			Description       string    `json:"description"`
			Tags              string    `json:"tags"`
			Image             string    `json:"image"`
			Icon              string    `json:"icon"`
			HeaderImage       string    `json:"headerImage"`
			Layout            string    `json:"layout"`
			Active            bool      `json:"active"`
			Closed            bool      `json:"closed"`
			Archived          bool      `json:"archived"`
			New               bool      `json:"new"`
			Featured          bool      `json:"featured"`
			Restricted        bool      `json:"restricted"`
			IsTemplate        bool      `json:"isTemplate"`
			TemplateVariables string    `json:"templateVariables"`
			PublishedAt       string    `json:"publishedAt"`
			CreatedBy         string    `json:"createdBy"`
			UpdatedBy         string    `json:"updatedBy"`
			CreatedAt         time.Time `json:"createdAt"`
			UpdatedAt         time.Time `json:"updatedAt"`
			CommentsEnabled   bool      `json:"commentsEnabled"`
			ImageOptimized    struct {
				ID                        string `json:"id"`
				ImageURLSource            string `json:"imageUrlSource"`
				ImageURLOptimized         string `json:"imageUrlOptimized"`
				ImageSizeKbSource         int    `json:"imageSizeKbSource"`
				ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
				ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
				ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
				RelID                     int    `json:"relID"`
				Field                     string `json:"field"`
				Relname                   string `json:"relname"`
			} `json:"imageOptimized"`
			IconOptimized struct {
				ID                        string `json:"id"`
				ImageURLSource            string `json:"imageUrlSource"`
				ImageURLOptimized         string `json:"imageUrlOptimized"`
				ImageSizeKbSource         int    `json:"imageSizeKbSource"`
				ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
				ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
				ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
				RelID                     int    `json:"relID"`
				Field                     string `json:"field"`
				Relname                   string `json:"relname"`
			} `json:"iconOptimized"`
			HeaderImageOptimized struct {
				ID                        string `json:"id"`
				ImageURLSource            string `json:"imageUrlSource"`
				ImageURLOptimized         string `json:"imageUrlOptimized"`
				ImageSizeKbSource         int    `json:"imageSizeKbSource"`
				ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
				ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
				ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
				RelID                     int    `json:"relID"`
				Field                     string `json:"field"`
				Relname                   string `json:"relname"`
			} `json:"headerImageOptimized"`
		} `json:"collections"`
		Categories []struct {
			ID             string    `json:"id"`
			Label          string    `json:"label"`
			ParentCategory string    `json:"parentCategory"`
			Slug           string    `json:"slug"`
			PublishedAt    string    `json:"publishedAt"`
			CreatedBy      string    `json:"createdBy"`
			UpdatedBy      string    `json:"updatedBy"`
			CreatedAt      time.Time `json:"createdAt"`
			UpdatedAt      time.Time `json:"updatedAt"`
		} `json:"categories"`
		Tags []struct {
			ID          string    `json:"id"`
			Label       string    `json:"label"`
			Slug        string    `json:"slug"`
			ForceShow   bool      `json:"forceShow"`
			PublishedAt string    `json:"publishedAt"`
			CreatedBy   int       `json:"createdBy"`
			UpdatedBy   int       `json:"updatedBy"`
			CreatedAt   time.Time `json:"createdAt"`
			UpdatedAt   time.Time `json:"updatedAt"`
			ForceHide   bool      `json:"forceHide"`
			IsCarousel  bool      `json:"isCarousel"`
		} `json:"tags"`
		CommentCount int `json:"commentCount"`
		Chats        []struct {
			ID           string    `json:"id"`
			ChannelID    string    `json:"channelId"`
			ChannelName  string    `json:"channelName"`
			ChannelImage string    `json:"channelImage"`
			Live         bool      `json:"live"`
			StartTime    time.Time `json:"startTime"`
			EndTime      time.Time `json:"endTime"`
		} `json:"chats"`
	} `json:"series"`
	Categories []struct {
		ID             string    `json:"id"`
		Label          string    `json:"label"`
		ParentCategory string    `json:"parentCategory"`
		Slug           string    `json:"slug"`
		PublishedAt    string    `json:"publishedAt"`
		CreatedBy      string    `json:"createdBy"`
		UpdatedBy      string    `json:"updatedBy"`
		CreatedAt      time.Time `json:"createdAt"`
		UpdatedAt      time.Time `json:"updatedAt"`
	} `json:"categories"`
	Collections []struct {
		ID                string    `json:"id"`
		Ticker            string    `json:"ticker"`
		Slug              string    `json:"slug"`
		Title             string    `json:"title"`
		Subtitle          string    `json:"subtitle"`
		CollectionType    string    `json:"collectionType"`
		Description       string    `json:"description"`
		Tags              string    `json:"tags"`
		Image             string    `json:"image"`
		Icon              string    `json:"icon"`
		HeaderImage       string    `json:"headerImage"`
		Layout            string    `json:"layout"`
		Active            bool      `json:"active"`
		Closed            bool      `json:"closed"`
		Archived          bool      `json:"archived"`
		New               bool      `json:"new"`
		Featured          bool      `json:"featured"`
		Restricted        bool      `json:"restricted"`
		IsTemplate        bool      `json:"isTemplate"`
		TemplateVariables string    `json:"templateVariables"`
		PublishedAt       string    `json:"publishedAt"`
		CreatedBy         string    `json:"createdBy"`
		UpdatedBy         string    `json:"updatedBy"`
		CreatedAt         time.Time `json:"createdAt"`
		UpdatedAt         time.Time `json:"updatedAt"`
		CommentsEnabled   bool      `json:"commentsEnabled"`
		ImageOptimized    struct {
			ID                        string `json:"id"`
			ImageURLSource            string `json:"imageUrlSource"`
			ImageURLOptimized         string `json:"imageUrlOptimized"`
			ImageSizeKbSource         int    `json:"imageSizeKbSource"`
			ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
			ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
			ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
			RelID                     int    `json:"relID"`
			Field                     string `json:"field"`
			Relname                   string `json:"relname"`
		} `json:"imageOptimized"`
		IconOptimized struct {
			ID                        string `json:"id"`
			ImageURLSource            string `json:"imageUrlSource"`
			ImageURLOptimized         string `json:"imageUrlOptimized"`
			ImageSizeKbSource         int    `json:"imageSizeKbSource"`
			ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
			ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
			ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
			RelID                     int    `json:"relID"`
			Field                     string `json:"field"`
			Relname                   string `json:"relname"`
		} `json:"iconOptimized"`
		HeaderImageOptimized struct {
			ID                        string `json:"id"`
			ImageURLSource            string `json:"imageUrlSource"`
			ImageURLOptimized         string `json:"imageUrlOptimized"`
			ImageSizeKbSource         int    `json:"imageSizeKbSource"`
			ImageSizeKbOptimized      int    `json:"imageSizeKbOptimized"`
			ImageOptimizedComplete    bool   `json:"imageOptimizedComplete"`
			ImageOptimizedLastUpdated string `json:"imageOptimizedLastUpdated"`
			RelID                     int    `json:"relID"`
			Field                     string `json:"field"`
			Relname                   string `json:"relname"`
		} `json:"headerImageOptimized"`
	} `json:"collections"`
	Tags []struct {
		ID          string    `json:"id"`
		Label       string    `json:"label"`
		Slug        string    `json:"slug"`
		ForceShow   bool      `json:"forceShow"`
		PublishedAt string    `json:"publishedAt"`
		CreatedBy   int       `json:"createdBy"`
		UpdatedBy   int       `json:"updatedBy"`
		CreatedAt   time.Time `json:"createdAt"`
		UpdatedAt   time.Time `json:"updatedAt"`
		ForceHide   bool      `json:"forceHide"`
		IsCarousel  bool      `json:"isCarousel"`
	} `json:"tags"`
	Cyom                  bool      `json:"cyom"`
	ClosedTime            time.Time `json:"closedTime"`
	ShowAllOutcomes       bool      `json:"showAllOutcomes"`
	ShowMarketImages      bool      `json:"showMarketImages"`
	AutomaticallyResolved bool      `json:"automaticallyResolved"`
	EnableNegRisk         bool      `json:"enableNegRisk"`
	AutomaticallyActive   bool      `json:"automaticallyActive"`
	EventDate             string    `json:"eventDate"`
	StartTime             time.Time `json:"startTime"`
	EventWeek             int       `json:"eventWeek"`
	SeriesSlug            string    `json:"seriesSlug"`
	Score                 string    `json:"score"`
	Elapsed               string    `json:"elapsed"`
	Period                string    `json:"period"`
	Live                  bool      `json:"live"`
	Ended                 bool      `json:"ended"`
	FinishedTimestamp     time.Time `json:"finishedTimestamp"`
	GmpChartMode          string    `json:"gmpChartMode"`
	EventCreators         []struct {
		ID            string    `json:"id"`
		CreatorName   string    `json:"creatorName"`
		CreatorHandle string    `json:"creatorHandle"`
		CreatorURL    string    `json:"creatorUrl"`
		CreatorImage  string    `json:"creatorImage"`
		CreatedAt     time.Time `json:"createdAt"`
		UpdatedAt     time.Time `json:"updatedAt"`
	} `json:"eventCreators"`
	TweetCount int `json:"tweetCount"`
	Chats      []struct {
		ID           string    `json:"id"`
		ChannelID    string    `json:"channelId"`
		ChannelName  string    `json:"channelName"`
		ChannelImage string    `json:"channelImage"`
		Live         bool      `json:"live"`
		StartTime    time.Time `json:"startTime"`
		EndTime      time.Time `json:"endTime"`
	} `json:"chats"`
	FeaturedOrder  int    `json:"featuredOrder"`
	EstimateValue  bool   `json:"estimateValue"`
	CantEstimate   bool   `json:"cantEstimate"`
	EstimatedValue string `json:"estimatedValue"`
	Templates      []struct {
		ID               string `json:"id"`
		EventTitle       string `json:"eventTitle"`
		EventSlug        string `json:"eventSlug"`
		EventImage       string `json:"eventImage"`
		MarketTitle      string `json:"marketTitle"`
		Description      string `json:"description"`
		ResolutionSource string `json:"resolutionSource"`
		NegRisk          bool   `json:"negRisk"`
		SortBy           string `json:"sortBy"`
		ShowMarketImages bool   `json:"showMarketImages"`
		SeriesSlug       string `json:"seriesSlug"`
		Outcomes         string `json:"outcomes"`
	} `json:"templates"`
	SpreadsMainLine              int       `json:"spreadsMainLine"`
	TotalsMainLine               int       `json:"totalsMainLine"`
	CarouselMap                  string    `json:"carouselMap"`
	PendingDeployment            bool      `json:"pendingDeployment"`
	Deploying                    bool      `json:"deploying"`
	DeployingTimestamp           time.Time `json:"deployingTimestamp"`
	ScheduledDeploymentTimestamp time.Time `json:"scheduledDeploymentTimestamp"`
	GameStatus                   string    `json:"gameStatus"`
}
